### ISSUE TITLE
Timer keeps display on and thus drains battery

### ISSUE THREAD

**Issue by moWerk** [AsteroidOS/asteroid-timer#6]
If this is a feature it should be changed so that the display suspends after normal timeout and the timer continues to run in the background.
Tested on lenok and dory nightly 20180115

**Comment by FlorentRevest** [comment]
Hi @eLtMosen,

Thank you for bringing that up but unfortunately this is the "expected" (I should say "accepted" instead) behavior. The problem is much more complex than it seems and also related to your other issue https://github.com/AsteroidOS/asteroid-timer/issues/5 .

Basically, we used to have asteroid-timer running in background (back in the time when there was an app switcher) however, when the watch entered a suspend state, it would stop counting and the alarm wouldn't be triggered before the watch was manually woken up (cf. https://github.com/AsteroidOS/asteroid-timer/issues/3 ). This made the app pretty much unusable and I tried a few workarounds:

- Scheduling a wakeup
    - Relying on timed to setup a CPU wakeup at a certain time and trigger some kind of alarm (for instance, this is what asteroid-alarmclock does and it works well). This would "work" but it can only configure that kind of alarms with a minute based precision and asteroid-timer requires second based precision.
        - If you think modifying timed is a good idea, I'll let you try to understand [its codebase]
(https://git.merproject.org/mer-core/mce/tree/master). Trust me, you'd need the help of a psychiatrist.
        - Triggering a service the minute before the timer elapses that would prevent the watch from sleeping for the few remaining seconds. This would work but this is starting to get very complex because you need to sync the state of asteroid-timer, timed and this utility. Again, a psychiatrist would help.
    - Relying on systemd-timer to setup a CPU wakeup at a certain time. This work is pushed in  [a branch](https://github.com/AsteroidOS/asteroid-timer/commit/938db420dabeb7312eec266183487b0961ad6fb5) just in case someone wants to continue my experiment. This also sounds great on paper but it would just not work at all (systemd-timer wouldn't wake the watch).
- Preventing the CPU from entering deep sleep. At this point, you can already feel that it gets dirty.
    - We could potentially have a daemon that runs in background and keeps a wakelock on while the timer is counting but I bet there would be lots of complaints about battery life sucking without any apparent reason. This is a complex solution (again, we need to keep everything synced) for a result that is very slightly better than what we have now.
    - Let asteroid-timer itself prevent the watch from suspending the CPU. Now, you also need to take into account that when the display turns off, asteroid-launcher kills the current foreground app so that the memory doesn't get fragmented with rests of apps partially running. This means that if you want to keep asteroid-timer running, you also need to stop the screen suspend mechanism. It sucks, I agree, but at least it is a [simple workaround](https://github.com/AsteroidOS/asteroid-timer/commit/c6ceead8052075dd5ff55f7dae0704edc875ff1b) that doesn't cause unexpected side effects. It also "works", i.e: asteroid-timer does what it is supposed to do.

Unfortunately there is no magic solution and for the time being, I chose to implement the last one mainly because of time constraints. If anyone has a better idea or feels like contributing something better, feel free to PR.

**Comment by moWerk** [comment]
Perfect, much appreciated.
I then vote to not include the timer in its current state to asteroid 1.0 release.
It would lower the overall very good impression that (even) more casual and/or demanding users would get from an "official" app with unexpected but accepted behaviour ;)
Also i concur that it is a low priority issue.

After your kind elaboration i got the idea that it might be less complicated if the OS sync client app could host the actual timer and asteroid-timer picking up/syncing current states on app start and gets a ping from asteroidos-sync app if timers run out for alarms to happen?
The downside would be no alarm on the watch if os sync is disconnected obviously.
